fork = false
frame = "full"
idle = true
maximized = false
no-multigrid = false
srgb = true
tabs = false
mouse-cursor-icon = "arrow"
vsync = true
wsl = false

[font]
normal = ["JetBrainsMono Nerd Font"]
size = 13
hinting = "slight"
edging = "subpixelantialias"
