gui:
  scrollHeight: 1
  scrollPastBottom: false
  scrollOffMargin: 2
  scrollOffBehavior: margin
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  sidePanelWidth: 0.35
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
  commitLength:
    show: true
  showListFooter: true
  showFileTree: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: false
  showPanelJumps: true
  nerdFontsVersion: "3"
  showFileIcons: true
  commitAuthorShortLength: 2
  commitAuthorLongLength: 17
  commitHashLength: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: none
  commandLogSize: 8
  splitDiff: auto
  screenMode: normal
  border: rounded
  animateExplosion: true
  portraitMode: auto
  filterMode: fuzzy
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 100
  statusPanelView: dashboard
git:
  pagers:
    - colorArg: always
      pager: ""
      useConfig: false
      externalDiffCommand: ""
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  merging:
    manualCommit: false
    args: ""
    squashMergeMessage: Squash merge {{selectedRef}} into {{currentBranch}}
  mainBranches:
    - master
    - main
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  overrideGpg: false
  disableForcePushing: false
  commitPrefix:
    - pattern: ""
      replace: ""
  branchPrefix: ""
  parseEmoji: false
  log:
    showWholeGraph: false
  truncateCopiedCommitHashesTo: 12
update:
  method: prompt
  days: 1
refresher:
  refreshInterval: 10
  fetchInterval: 60
confirmOnQuit: false
quitOnTopLevelReturn: false
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: ""
  openDirInEditor: ""
  editPreset: ""
  open: "xdg-open {{filename}}"
  openLink: ""
  copyToClipboardCmd: ""
  readFromClipboardCmd: ""
disableStartupPopups: true
notARepository: prompt
promptToReturnFromSubprocess: true
