bind = SUPER, T, exec, xdg-terminal-exec
bind = SUPER, Super_L, exec, pgrep tofi-drun &>/dev/null && killall tofi-drun || tofi-drun --placeholder-text="Applications"
bind = SUPER, Return, layoutmsg, swapwithmaster
bind = SUPER, Q, exec, pgrep wlogout && killall wlogout || wlogout -b 2
bind = SUPER, F, fullscreen, 1
bind = SUPER, R, exec, eval "$(tofi-run --placeholder-text="run" 2> /dev/null)" &> /dev/null &
bind = ALT, F4, killactive,
bindel = , XF86AudioRaiseVolume, exec, amixer -q sset Master 1%+
bindel = , XF86AudioLowerVolume, exec, amixer -q sset Master 1%-
bindel = , XF86AudioMute, exec, amixer -q sset Master toggle
bind = , Print, exec, grimblast --notify --freeze copysave area

bind = ALT, L, exec, _movefocus -r
bind = ALT, H, exec, _movefocus -l
bind = ALT, K, exec, _movefocus -u
bind = ALT, J, exec, _movefocus -d
bind = SUPER, L, exec, _workspace --next
bind = SUPER, H, exec, _workspace --prev
bind = SUPER SHIFT, L, exec, _workspace --next --move
bind = SUPER SHIFT, H, exec, _workspace --prev --move

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
