bind = SUPER, Return, exec, xdg-terminal-exec
bind = SUPER, Super_L, exec, pgrep tofi-drun &>/dev/null && killall tofi-drun || tofi-drun
bind = SUPER, R, exec, eval "$(tofi-run 2> /dev/null)" &> /dev/null &
bind = SUPER, Q, exec, pgrep wlogout && killall wlogout || wlogout -b 2
bind = SUPER, F, fullscreen, 1
bind = , F11, fullscreen, 0
bind = SUPER SHIFT, F, togglefloating,  
bind = ALT, F4, killactive,

bind = ALT, L, exec, hypr-movefocus -r
bind = ALT, H, exec, hypr-movefocus -l
bind = ALT, K, exec, hypr-movefocus -u
bind = ALT, J, exec, hypr-movefocus -d

bind = SUPER, H, workspace, 1
bind = SUPER, J, workspace, 2
bind = SUPER, K, workspace, 3
bind = SUPER, L, workspace, 4
bind = SUPER, SEMICOLON, workspace, 5

bind = SUPER SHIFT, H, movetoworkspace, 1
bind = SUPER SHIFT, J, movetoworkspace, 2
bind = SUPER SHIFT, K, movetoworkspace, 3
bind = SUPER SHIFT, L, movetoworkspace, 4
bind = SUPER SHIFT, SEMICOLON, movetoworkspace, 5

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bindel = , XF86AudioRaiseVolume, exec, amixer -q sset Master 1%+
bindel = , XF86AudioLowerVolume, exec, amixer -q sset Master 1%-
bindel = , XF86AudioMute, exec, amixer -q sset Master toggle
bindl = , Print, exec, grimblast --notify --freeze copysave area
