# if tpm is not available, install it
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# unbind all keybindings
unbind-key -a

# plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'christoomey/vim-tmux-navigator'
set-option -g @plugin 'catppuccin/tmux'
set-option -g @plugin 'tmux-plugins/tmux-yank'

# options
set-option -g default-terminal 'tmux-256color'
set-option -as terminal-overrides ",xterm-kitty:RGB"
set-option -g status-interval 1
set-option -g repeat-time 500
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g default-shell '/usr/bin/zsh'
set-option -g destroy-unattached on
set-window-option -g mode-keys vi
set-window-option -g pane-base-index 1

# Ctrl+Space as prefix
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# theme and statusbar
set-option -g @catppuccin_flavour 'mocha'
set-option -g @catppuccin_window_right_separator "█ "
set-option -g @catppuccin_window_number_position "left"
set-option -g @catppuccin_window_middle_separator "  "
set-option -g @catppuccin_window_default_fill "none"
set-option -g @catppuccin_window_current_fill "all"
set-option -g @catppuccin_status_modules_right "application"
set-option -g @catppuccin_application_icon " "
set-option -g @catppuccin_status_left_separator "█"
set-option -g @catppuccin_status_right_separator "█"
set-option -g @catppuccin_window_default_text "#W"
set-option -g @catppuccin_window_current_text "#W"
set-option -g @catppuccin_window_current_color "#{thm_magenta}"

# keybindings
bind-key -r h select-pane -L
bind-key -r j select-pane -D 
bind-key -r k select-pane -U
bind-key -r l select-pane -R

bind-key -r H previous-window
bind-key -r L next-window

bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi i send-keys -X cancel
bind-key -T copy-mode-vi a send-keys -X cancel

bind-key 'c' new-window -a
bind-key '_' split-window -v
bind-key '|' split-window -h

run '~/.tmux/plugins/tpm/tpm'
