# >>> Unbind All Keybindings >>>
unbind-key -a
# <<< Unbind All Keybindings <<<


#############
## Options ##
#############
set-option -g default-terminal 'tmux-256color'
# set-option -as terminal-overrides ",xterm-kitty:Tc"
set-option -sa terminal-overrides ",xterm-256color:Tc" # temporarily for windows terminal
set-option -s escape-time 0
set-option -g history-limit 50000
set-option -g focus-events on
set-option -g status-interval 1
set-option -g repeat-time 500
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g default-shell '/usr/bin/zsh'
set-window-option -g mode-keys vi
set-window-option -g pane-base-index 1

# >>> Prefix >>>
set-option -g prefix C-Space
bind-key C-Space send-prefix
# <<< Prefix <<<

#########################
## Theme and Statusbar ##
#########################
set-option -g status-position "bottom"
set-option -g status-style bg=#181825,fg=#6c7086
set-option -g status-justify "left"
set-option -g status-left "#{?client_prefix,#[fg=#89b4fa],#[fg=#f9e2af]}█"
set-option -g status-right "#{?client_prefix,#[fg=#89b4fa],#[fg=#f9e2af]}  █"
set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format "#[fg=#f9e2af] #I:#W "
set-option -g display-time 1

#################
## Keybindings ##
#################
bind-key -r H previous-window
bind-key -r L next-window

# >>> resize mode >>>
bind-key -T prefix r {
  set-option prefix None
  set-option key-table resize
  select-pane -d
  set-option status-left "#[fg=#f38ba8]█"
  set-option status-right "#[fg=#f38ba8]󰩨  █"
  set-option window-status-current-format "#[fg=#f38ba8] #I:#W "
  refresh-client -S
}

bind-key -T resize Escape {
  set-option -u prefix
  set-option -u key-table
  select-pane -e
  set-option -u status-left
  set-option -u status-right
  set-option -u window-status-current-format
  refresh-client -S
}

bind-key -r -T resize j resize-pane -D 2
bind-key -r -T resize k resize-pane -U 2
bind-key -r -T resize h resize-pane -L 2
bind-key -r -T resize l resize-pane -R 2
# <<< resize mode <<<

# >>> copy mode >>>
copymode_enabled="! ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf|less|.?top)(diff)?$'"

bind-key -T prefix v if-shell "$copymode_enabled" {
  set-option prefix None
  select-pane -d
  set-option status-left "#[fg=#a6e3a1]█"
  set-option status-right "#[fg=#a6e3a1]  █"
  set-option window-status-current-format "#[fg=#a6e3a1] #I:#W "
  refresh-client -S
  copy-mode -H
}

bind-key -T copy-mode-vi i {
  set-option -u prefix
  select-pane -e
  send-keys -X cancel
  set-option -u status-left
  set-option -u status-right
  set-option -u window-status-current-format
  refresh-client -S
}

bind-key -T copy-mode-vi a {
  set-option -u prefix
  select-pane -e
  send-keys -X cancel
  set-option -u status-left
  set-option -u status-right
  set-option -u window-status-current-format
  refresh-client -S
}

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# <<< copy mode <<<

bind-key c new-window -c "#{pane_current_path}"
bind-key s run-shell "~/.config/tmux/scripts/smart-split"
bind-key "|" split-pane -h -c "#{pane_current_path}"
bind-key "_" split-pane -c "#{pane_current_path}"

#############
## Plugins ##
#############
run '~/.config/tmux/scripts/tmux-yank/yank.tmux'
run '~/.config/tmux/scripts/tmux-navigator/navigator.tmux'
