# unbind all keybindings
unbind-key -a

# options
set-option -g default-terminal 'tmux-256color'
set-option -as terminal-overrides ",xterm-kitty:RGB"
set-option -s escape-time 0
set-option -g history-limit 50000
set-option -g focus-events on
set-option -g status-interval 1
set-option -g repeat-time 500
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g default-shell '/usr/bin/zsh'
set-option -g destroy-unattached on
set-window-option -g mode-keys vi
set-window-option -g pane-base-index 1

# Ctrl+Space as prefix
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# theme and statusbar
set-option -g status-position "bottom"
set-option -g status-style bg=#1e1e2e,fg=#6c7086
set-option -g status-justify "left"
set-option -g status-left ""
set-option -g status-right ""
set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format "#[fg=#f9e2af] #I:#W "
set-option -g message-style fg=#f38ba8
set-option -g display-time 500

# keybindings
bind-key -r H previous-window
bind-key -r L next-window

bind-key -r h resize-pane -L 2
bind-key -r j resize-pane -D 2
bind-key -r k resize-pane -U 2
bind-key -r l resize-pane -R 2

bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi i send-keys -X cancel
bind-key -T copy-mode-vi a send-keys -X cancel

bind-key c new-window -c "#{pane_current_path}"
bind-key s run-shell "~/.config/tmux/scripts/smart-split.tmux"

# plugins
run '~/.config/tmux/scripts/tmux-yank/yank.tmux'
run '~/.config/tmux/scripts/tmux-navigator/navigator.tmux'
