{ ... }:
{
  imports = [
    ./hardware-configuration.nix # Generated by the system
    ./hardware.nix
    ../../modules/boot.nix
    ../../modules/networking.nix
    ../../modules/shell.nix
    ../../modules/desktop.nix
    ../../modules/users.nix
    ../../modules/development.nix
    ../../modules/packages.nix
  ];

  networking.hostName = "hp450";
  system.stateVersion = "25.11";
}
