#!/bin/env bash

function set_mode_options {
  color="$1"
  
  tmux set-option prefix None
  tmux select-pane -d
  tmux set-option status-right " #[fg=${color}]  #[fg=#89b4fa]█"
  tmux refresh-client -S
}

function undo_mode_options {
  tmux set-option -u prefix
  tmux select-pane -e
  tmux set-option -u status-right
  tmux refresh-client -S
}

function main {
  case "$(tmux display-message -p '#{pane_mode}')" in
    copy-mode )
      set_mode_options '#a6e3a1'
      ;;
    tree-mode | buffer-mode | client-mode )
      set_mode_options '#f9e2af'
      ;;
    * )
      undo_mode_options
      ;;
  esac
}

main 
