#!/bin/env bash

case "$(tmux display-message -p '#{pane_mode}')" in
  copy-mode )
    tmux set-option prefix None
    tmux select-pane -d
    tmux set-option window-status-current-style fg=#a6e3a1
    tmux set-option status-left "#[fg=#a6e3a1]█ "
    tmux set-option status-right " #[fg=#a6e3a1]  █"
    tmux refresh-client -S
    ;;
  tree-mode | buffer-mode | client-mode )
    tmux set-option prefix None
    tmux select-pane -d
    tmux set-option window-status-current-style fg=#f5c2e7
    tmux set-option status-left "#[fg=#f5c2e7]█ "
    tmux set-option status-right " #[fg=#f5c2e7]  █"
    tmux refresh-client -S
    ;;
  * )
    tmux set-option -u prefix
    tmux select-pane -e
    tmux set-option -u window-status-current-style
    tmux set-option -u status-left
    tmux set-option -u status-right
    tmux refresh-client -S
    ;;
esac
