#!/usr/bin/env python3

import json
import os
import shlex
import shutil
import subprocess


class CommandNotFoundError(Exception):
    """shell command not found"""


def get_window_dimension(inblock: bool = False) -> tuple[int, int]:
    if not inblock:
        if not shutil.which("hyprctl"):
            raise CommandNotFoundError("`hyprctl` command not found")

        return tuple(
            json.loads(
                subprocess.run(
                    shlex.split("hyprctl activewindow -j"), capture_output=True
                ).stdout
            )["size"]
        )

    window_width_block: int = int(
        subprocess.run(
            shlex.split("tmux display-message -p '#{client_width}'"),
            capture_output=True,
        ).stdout
    )
    window_height_block: int = int(
        subprocess.run(
            shlex.split("tmux display-message -p '#{client_height}'"),
            capture_output=True,
        ).stdout
    )
    return (window_width_block, window_height_block)


def get_pane_dimension() -> tuple[int, int]:
    pane_width: int = int(
        subprocess.run(
            shlex.split("tmux display-message -p '#{pane_width}'"), capture_output=True
        ).stdout
    )
    pane_height: int = int(
        subprocess.run(
            shlex.split("tmux display-message -p '#{pane_height}'"), capture_output=True
        ).stdout
    )

    return (pane_width, pane_height)


def get_block_dimension() -> tuple[float, float]:
    window_dimension_px: tuple[int, int] = get_window_dimension(inblock=False)
    window_dimension_block: tuple[int, int] = get_window_dimension(inblock=True)

    return (
        window_dimension_px[0] / window_dimension_block[0],
        window_dimension_px[1] / window_dimension_block[1],
    )


def main() -> None:
    # skip if not inside tmux
    if not os.environ.get("TMUX"):
        return

    try:
        block_dimension: tuple[float, float] = get_block_dimension()
        pane_dimension: tuple[float, float] = get_pane_dimension()
        if (
            block_dimension[0] * pane_dimension[0]
            > block_dimension[1] * pane_dimension[1]
        ):
            subprocess.run(["tmux split-pane -h -c '#{pane_current_path}'"], shell=True)
            return

        subprocess.run(["tmux split-pane -c '#{pane_current_path}'"], shell=True)

    except CommandNotFoundError as ex:
        subprocess.run(["tmux split-pane -h -c '#{pane_current_path}'"], shell=True)


if __name__ == "__main__":
    main()
